version: '3'

services:
  mongodb:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootnmbp
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./nmbpdata:/nmbpdata

  springboot-docker-compose:
    image: springboot-docker-compose:latest
    container_name: "springboot-docker-compose"
    ports:
      - 8080:8080
    links:
      - mongodb

volumes:
  mongodb_data: